esphome:
  name: esphome-bm2-ble
  friendly_name: ESPHome BM2 BLE
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
## external_components removed for local testing

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASS"

logger:
  level: DEBUG

esp32_ble_tracker:

ble_client:
  - mac_address: "00:00:00:00:00:00"
    id: blm2_ble_client

bm2_ble:
  id: blm2_ble_id
  ble_client_id: blm2_ble_client
  update_interval: 10s

## ota removed for test validation
sensor:
  - platform: bm2_ble
    id: bm2_voltage
    name: "BM2 Voltage"
    role: voltage
    bm2_ble_id: blm2_ble_id

  - platform: bm2_ble
    id: bm2_battery
    name: "BM2 Battery Percent"
    role: battery
    bm2_ble_id: blm2_ble_id

text_sensor:
  - platform: bm2_ble
    id: bm2_status
    name: "BM2 Status"
    type: status
    bm2_ble_id: blm2_ble_id
