# Copilot/Developer Notes:
# - This example targets a Lolin S3 Pro (ESP32-S3) board using the ESP-IDF framework.
# - Set `min_version: 2025.11.0` to ensure features/compatibility.
# - Use `esphome run bm2_example.yaml --device COMn` (Windows) or `esphome run bm2_example.yaml --device /dev/ttyUSBn` (Linux/macOS) to build & flash.
# - For development, see `bm2_example_test.yaml` for a reduced, local test example.


esphome:
  # Required ESPhome minimum version for compatibility
  name: esphome-bm2-ble
  friendly_name: ESPHome BM2 BLE
  # This project is built for ESPhome 2025.11 (or newer) and uses the ESP-IDF framework
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  # Use the Lolin S3 Pro board (ESP32-S3) with the ESP-IDF framework
  # If you are using a different board, update this field accordingly.
  board: lolin_s3_pro
  framework:
    type: esp-idf
    
external_components:
  - source: github://andrewbackway/esphome-bm2_ble@main

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASS"

logger:
  level: DEBUG

esp32_ble_tracker:

ble_client:
  - mac_address: "XX:XX:XX:XX:XX:XX"
    id: blm2_ble_client


bm2_ble:
  id: blm2_ble_id
  ble_client_id: blm2_ble_client
  update_interval: 10s

ota:

sensor:
  - platform: bm2_ble
    id: bm2_voltage
    name: "BM2 Voltage"

  - platform: bm2_ble
    id: bm2_battery
    name: "BM2 Battery Percent"

text_sensor:
  - platform: bm2_ble
    id: bm2_status
    name: "BM2 Status"
