
esphome:
  name: esphome-bm2-ble
  friendly_name: ESPHome BM2 BLE
  min_version: 2025.5.0
  name_add_mac_suffix: false


external_components:
  - source: github://andrewbackway/esphome-bm2_ble@main

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASS"

logger:
  level: DEBUG

esp32_ble_tracker:

ble_client:
  - mac_address: "XX:XX:XX:XX:XX:XX"
    id: blm2_ble_client


bm2_ble:
  id: blm2_ble_id
  ble_client_id: blm2_ble_client
  update_interval: 10s

ota:

sensor:
  - platform: bm2_ble
    id: bm2_voltage
    name: "BM2 Voltage"

  - platform: bm2_ble
    id: bm2_battery
    name: "BM2 Battery Percent"

text_sensor:
  - platform: bm2_ble
    id: bm2_status
    name: "BM2 Status"
